#!/bin/bash
# tools/gen_consts.sh
# Generate FASM include file from Brainlib JSONs
# Usage: ./tools/gen_consts.sh > Brainlib/brainlib.inc

echo "; Generated by tools/gen_consts.sh"
echo "; Date: $(date)"

# Function to process a single JSON file
process_file() {
    local filepath="$1"
    local filename=$(basename "$filepath")

    echo ""
    echo "; ----------------------------------------------------------------"
    echo "; From $filename"
    echo "; ----------------------------------------------------------------"

    local mnemonic=""
    local name=""
    local kind=""
    local value=""
    local hint=""
    local in_block=0

    # Read file line by line
    while IFS= read -r line; do
        # Strip whitespace
        line=$(echo "$line" | sed 's/^[ \t]*//;s/[ \t]*$//')

        if [[ "$line" == "{" ]]; then
            in_block=1
            mnemonic=""
            name=""
            kind=""
            value=""
            hint=""
        elif [[ "$line" == "}," ]] || [[ "$line" == "}" ]]; then
            if [[ "$in_block" -eq 1 ]]; then
                # 1. Handle Terminal Constants (Legacy logic preserved for terminal.json)
                if [[ "$filename" == "terminal.json" && "$kind" == "const_str" ]]; then
                    # Remove quotes
                    val_content="${value%\"}"
                    val_content="${val_content#\"}"

                    # Check for \u001b
                    if [[ "$val_content" == *"\\u001b"* ]]; then
                        rest=${val_content/\\u001b/}
                        echo "str_${name} db 0x1b, '${rest}', 0"
                        echo "${name} equ str_${name}"
                    else
                        echo "str_${name} db '${val_content}', 0"
                        echo "${name} equ str_${name}"
                    fi
                fi

                # 2. Handle AI Hints (New logic for all files)
                # Determine key (mnemonic takes precedence, then name)
                local key=""
                if [[ -n "$mnemonic" ]]; then
                    key="$mnemonic"
                elif [[ -n "$name" ]]; then
                    key="$name"
                fi

                if [[ -n "$key" && -n "$hint" ]]; then
                    # Remove quotes from hint
                    hint_content="${hint%\"}"
                    hint_content="${hint_content#\"}"

                    # Sanitize key for FASM label (replace . with _)
                    local label_key=$(echo "$key" | tr '.' '_')

                    # Output hint constant
                    echo "hint_${label_key} db '${hint_content}', 0"
                fi
            fi
            in_block=0
        else
            # Extract fields using Regex
            if [[ "$line" =~ \"mnemonic\":\ \"([^\"]+)\" ]]; then
                mnemonic="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ \"name\":\ \"([^\"]+)\" ]]; then
                name="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ \"kind\":\ \"([^\"]+)\" ]]; then
                kind="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ \"value\":\ \"(.*)\" ]]; then
                # String value
                value="\"${BASH_REMATCH[1]}\""
            elif [[ "$line" =~ \"hint\":\ \"(.*)\" ]]; then
                hint="\"${BASH_REMATCH[1]}\""
            fi

            # Handle numeric value if needed (though mostly for consts which might not need FASM output other than equ?)
            # Existing script didn't output numeric constants, only const_str for terminal.
            # If we need to output numeric constants as 'equ', we can add that logic.
            # For now, adhering to 'Code Honesty': replicate existing behavior + hints.
        fi
    done < "$filepath"
}

# Iterate over all JSON files in Brainlib
# Sort them to ensure deterministic output order
for f in $(ls Brainlib/*.json | sort); do
    process_file "$f"
done
