#!/bin/bash
# tools/gen_consts.sh
# Generate FASM include file from Brainlib JSONs
# Usage: ./tools/gen_consts.sh > brainlib.inc

echo "; Generated by tools/gen_consts.sh"

# Function to process terminal.json
process_terminal() {
    local name=""
    local kind=""
    local value=""
    local in_block=0

    # Read file line by line
    while IFS= read -r line; do
        # Strip whitespace
        line=$(echo "$line" | sed 's/^[ \t]*//;s/[ \t]*$//')

        if [[ "$line" == "{" ]]; then
            in_block=1
            name=""
            kind=""
            value=""
        elif [[ "$line" == "}," ]] || [[ "$line" == "}" ]]; then
            if [[ "$in_block" -eq 1 ]]; then
                if [[ "$kind" == "const_str" ]]; then
                    # Output FASM
                    # Convert \u001b to 0x1b
                    # Value format in JSON: "\u001b[31m"
                    # We want: db 0x1b, '[31m', 0

                    # Remove quotes
                    val_content="${value%\"}"
                    val_content="${val_content#\"}"

                    # Check for \u001b (literal backslash u 0 0 1 b)
                    if [[ "$val_content" == *"\\u001b"* ]]; then
                        # Replace \u001b with nothing to get the rest
                        rest=${val_content/\\u001b/}
                        echo "str_${name} db 0x1b, '${rest}', 0"
                        echo "${name} equ str_${name}"
                    else
                        echo "str_${name} db '${val_content}', 0"
                        echo "${name} equ str_${name}"
                    fi
                fi
            fi
            in_block=0
        else
            # Extract fields
            if [[ "$line" =~ \"name\":\ \"([^\"]+)\" ]]; then
                name="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ \"kind\":\ \"([^\"]+)\" ]]; then
                kind="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ \"value\":\ \"(.*)\" ]]; then
                # Value might contain escaped chars, grab content inside quotes
                # Simple regex grab
                value="${BASH_REMATCH[1]}"
                # Re-add quotes for processing logic above
                value="\"$value\""
            fi
        fi
    done < Brainlib/terminal.json
}

process_terminal
