#!/bin/bash
# Fixed generator - preserves dots in mnemonic strings and builds registry

echo "; Generated by tools/gen_consts.sh"
echo "; Date: $(date)"
echo ""

declare -A defined
REGISTRY_ENTRIES=""

for json in Brainlib/*.json; do
  echo "; From $(basename $json)"
  
  while IFS= read -r line; do
    if [[ $line =~ \"mnemonic\":\ *\"([^\"]+)\" ]]; then
      mnem="${BASH_REMATCH[1]}"
      label=$(echo "$mnem" | tr '.' '_')  # Label uses underscore
    elif [[ $line =~ \"hint\":\ *\"([^\"]+)\" ]]; then
      hint="${BASH_REMATCH[1]}"
    elif [[ $line =~ \"opcode\":\ *\"([^\"]+)\" ]]; then
      opcode="${BASH_REMATCH[1]}"
      
      if [[ -n $label && -z ${defined[str_$label]} ]]; then
        # Output hint if exists
        if [[ -n $hint ]]; then
          echo "hint_$label db '$hint', 0"
          defined[hint_$label]=1
        fi
        
        # Output mnemonic string (keep dots)
        echo "str_$label db '$mnem', 0"
        defined[str_$label]=1
        
        # Output opcode
        if [[ -n $opcode && -z ${defined[op_$label]} ]]; then
          echo "op_$label db $opcode"
          
          # Calculate opcode length
          op_len=$(echo "$opcode" | awk -F, '{print NF}')
          echo "len_$label dq $op_len"
          defined[op_$label]=1
          
          # Add to registry (only if has opcode - means it's an instruction)
          hint_ref="hint_$label"
          [[ -z ${defined[hint_$label]} ]] && hint_ref="0"
          
          REGISTRY_ENTRIES+="\n    dq str_$label\n    dq op_$label\n    dq $op_len\n    dq $hint_ref"
        fi
      fi
      mnem=""; hint=""; opcode=""; label=""
    fi
  done < "$json"
done

echo ""
echo "; ----------------------------------------------------------------"
echo "; Instruction Registry"
echo "; ----------------------------------------------------------------"
echo "instruction_registry:"
echo -e "$REGISTRY_ENTRIES"
echo "    dq 0 ; Terminator"
